"""Initial_migration

Revision ID: a5a1b33198f0
Revises: 
Create Date: 2025-12-19 15:07:52.933668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a1b33198f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_collection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('workflows_collected', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_collection_logs_id'), 'data_collection_logs', ['id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'platform', 'country', name='uq_workflow_platform_country')
    )
    op.create_index(op.f('ix_workflows_country'), 'workflows', ['country'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_normalized_name'), 'workflows', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_workflows_platform'), 'workflows', ['platform'], unique=False)
    op.create_table('popularity_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('like_to_view_ratio', sa.Float(), nullable=True),
    sa.Column('comment_to_view_ratio', sa.Float(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('unique_contributors', sa.Integer(), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('interest_score', sa.Integer(), nullable=True),
    sa.Column('trend_percentage', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'metric_date', name='uq_workflow_metric_date')
    )
    op.create_index(op.f('ix_popularity_metrics_id'), 'popularity_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_popularity_metrics_metric_date'), 'popularity_metrics', ['metric_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_popularity_metrics_metric_date'), table_name='popularity_metrics')
    op.drop_index(op.f('ix_popularity_metrics_id'), table_name='popularity_metrics')
    op.drop_table('popularity_metrics')
    op.drop_index(op.f('ix_workflows_platform'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_normalized_name'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_country'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_data_collection_logs_id'), table_name='data_collection_logs')
    op.drop_table('data_collection_logs')
    # ### end Alembic commands ###
